"""Native execution traces tools and benchmarks

Revision ID: 4666ed0d2d17
Revises: b02442d39feb
"""

import sqlalchemy as sa
from alembic import op

revision = "4666ed0d2d17"
down_revision = "b02442d39feb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "benchmark_profiles",
        sa.Column("model_id", sa.String(length=36), nullable=False),
        sa.Column("work_id", sa.String(length=36), nullable=False),
        sa.Column("suite_version", sa.String(length=100), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("checked_at", sa.Integer(), nullable=False),
        sa.Column("metrics", sa.JSON(), nullable=False),
        sa.Column("org_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["model_configs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["work_id"],
            ["agent_work.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("model_id"),
    )
    op.create_index(op.f("ix_benchmark_profiles_org_id"), "benchmark_profiles", ["org_id"], unique=False)
    op.create_table(
        "benchmark_results",
        sa.Column("work_id", sa.String(length=36), nullable=False),
        sa.Column("model_id", sa.String(length=36), nullable=False),
        sa.Column("case_name", sa.String(length=100), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("metrics", sa.JSON(), nullable=False),
        sa.Column("org_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["model_configs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["work_id"],
            ["agent_work.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("work_id", "case_name"),
    )
    op.create_index(op.f("ix_benchmark_results_model_id"), "benchmark_results", ["model_id"], unique=False)
    op.create_index(op.f("ix_benchmark_results_org_id"), "benchmark_results", ["org_id"], unique=False)
    op.create_index(op.f("ix_benchmark_results_work_id"), "benchmark_results", ["work_id"], unique=False)
    op.create_table(
        "run_traces",
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("state", sa.String(), nullable=False),
        sa.Column("preview", sa.Text(), nullable=False),
        sa.Column("event_count", sa.Integer(), nullable=False),
        sa.Column("tool_count", sa.Integer(), nullable=False),
        sa.Column("usage_known", sa.Boolean(), nullable=False),
        sa.Column("org_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["model_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id"),
    )
    op.create_index(op.f("ix_run_traces_org_id"), "run_traces", ["org_id"], unique=False)
    op.create_table(
        "tool_invocations",
        sa.Column("workflow_id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("agent_id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=True),
        sa.Column("call_id", sa.String(length=200), nullable=False),
        sa.Column("step_name", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("arguments", sa.JSON(), nullable=False),
        sa.Column("result", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("org_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["model_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workflow_id"],
            ["workflows.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workflow_id", "step_name", "call_id"),
    )
    op.create_index(op.f("ix_tool_invocations_org_id"), "tool_invocations", ["org_id"], unique=False)
    op.create_index(
        op.f("ix_tool_invocations_workflow_id"), "tool_invocations", ["workflow_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tool_invocations_workflow_id"), table_name="tool_invocations")
    op.drop_index(op.f("ix_tool_invocations_org_id"), table_name="tool_invocations")
    op.drop_table("tool_invocations")
    op.drop_index(op.f("ix_run_traces_org_id"), table_name="run_traces")
    op.drop_table("run_traces")
    op.drop_index(op.f("ix_benchmark_results_work_id"), table_name="benchmark_results")
    op.drop_index(op.f("ix_benchmark_results_org_id"), table_name="benchmark_results")
    op.drop_index(op.f("ix_benchmark_results_model_id"), table_name="benchmark_results")
    op.drop_table("benchmark_results")
    op.drop_index(op.f("ix_benchmark_profiles_org_id"), table_name="benchmark_profiles")
    op.drop_table("benchmark_profiles")
    # ### end Alembic commands ###
