"""approved workforce plans and distributed capacity

Revision ID: 8c922fd4eecf
Revises: dc1275532cfb
"""

import sqlalchemy as sa
from alembic import op

revision = "8c922fd4eecf"
down_revision = "dc1275532cfb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "staffing_plans",
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("content", sa.JSON(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("runtime", sa.JSON(), nullable=False),
        sa.Column("org_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id"),
    )
    op.create_index(op.f("ix_staffing_plans_org_id"), "staffing_plans", ["org_id"], unique=False)
    op.create_table(
        "staffing_revisions",
        sa.Column("plan_id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("content", sa.JSON(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("org_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["staffing_plans.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("plan_id", "version"),
    )
    op.create_index(op.f("ix_staffing_revisions_org_id"), "staffing_revisions", ["org_id"], unique=False)
    op.create_table(
        "task_assignments",
        sa.Column("task_id", sa.String(length=36), nullable=False),
        sa.Column("previous_agent_id", sa.String(length=36), nullable=False),
        sa.Column("agent_id", sa.String(length=36), nullable=False),
        sa.Column("owner_id", sa.String(length=36), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("org_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["previous_agent_id"],
            ["agents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_task_assignments_org_id"), "task_assignments", ["org_id"], unique=False)
    op.create_index(op.f("ix_task_assignments_task_id"), "task_assignments", ["task_id"], unique=False)
    op.add_column("workflows", sa.Column("capacity_agents", sa.JSON(), nullable=False, server_default="[]"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workflows", "capacity_agents")
    op.drop_index(op.f("ix_task_assignments_task_id"), table_name="task_assignments")
    op.drop_index(op.f("ix_task_assignments_org_id"), table_name="task_assignments")
    op.drop_table("task_assignments")
    op.drop_index(op.f("ix_staffing_revisions_org_id"), table_name="staffing_revisions")
    op.drop_table("staffing_revisions")
    op.drop_index(op.f("ix_staffing_plans_org_id"), table_name="staffing_plans")
    op.drop_table("staffing_plans")
    # ### end Alembic commands ###
