"""workflow concurrency constraints

Revision ID: 96a913864372
Revises: 5733038f8f8a
"""

from alembic import op

revision = "96a913864372"
down_revision = "5733038f8f8a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("uq_workflows_task", "workflows", ["task_id"], unique=True)
    op.create_index(
        "uq_workflows_requirement_revision", "workflows", ["requirement_id", "revision"], unique=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_index("uq_workflows_requirement_revision", table_name="workflows")
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_index("uq_workflows_task", table_name="workflows")
    # ### end Alembic commands ###
