"""provider vault policies and durable agent runtime

Revision ID: b02442d39feb
Revises: 771bb4c719ce
"""

import sqlalchemy as sa
from alembic import op

revision = "b02442d39feb"
down_revision = "771bb4c719ce"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "provider_credentials",
        sa.Column("provider_id", sa.String(length=36), nullable=False),
        sa.Column("ciphertext", sa.Text(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("org_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["providers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider_id"),
    )
    op.create_index(op.f("ix_provider_credentials_org_id"), "provider_credentials", ["org_id"], unique=False)
    op.create_table(
        "model_policies",
        sa.Column("scope", sa.String(length=100), nullable=False),
        sa.Column("preferred_model_id", sa.String(length=36), nullable=True),
        sa.Column("allowed_model_ids", sa.JSON(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("org_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["preferred_model_id"],
            ["model_configs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id", "scope"),
    )
    op.create_index(op.f("ix_model_policies_org_id"), "model_policies", ["org_id"], unique=False)
    op.create_table(
        "provider_probes",
        sa.Column("provider_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("checked_at", sa.Integer(), nullable=True),
        sa.Column("error_code", sa.String(), nullable=False),
        sa.Column("models", sa.JSON(), nullable=False),
        sa.Column("inference_at", sa.Integer(), nullable=True),
        sa.Column("inference_model_id", sa.String(length=36), nullable=True),
        sa.Column("org_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["inference_model_id"],
            ["model_configs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["providers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider_id"),
    )
    op.create_index(op.f("ix_provider_probes_org_id"), "provider_probes", ["org_id"], unique=False)
    op.create_table(
        "agent_work",
        sa.Column("workflow_id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=True),
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("subject_id", sa.String(length=36), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("participants", sa.JSON(), nullable=False),
        sa.Column("input", sa.JSON(), nullable=False),
        sa.Column("result", sa.JSON(), nullable=False),
        sa.Column("org_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workflow_id"],
            ["workflows.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workflow_id"),
    )
    op.create_index(op.f("ix_agent_work_org_id"), "agent_work", ["org_id"], unique=False)
    op.create_table(
        "agent_executions",
        sa.Column("workflow_id", sa.String(length=36), nullable=False),
        sa.Column("agent_id", sa.String(length=36), nullable=False),
        sa.Column("state", sa.String(), nullable=False),
        sa.Column("step_name", sa.String(length=100), nullable=False),
        sa.Column("model_run_id", sa.String(length=36), nullable=True),
        sa.Column("updated_at", sa.Integer(), nullable=False),
        sa.Column("detail", sa.JSON(), nullable=False),
        sa.Column("org_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["model_run_id"],
            ["model_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workflow_id"],
            ["workflows.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workflow_id", "agent_id"),
    )
    op.create_index(op.f("ix_agent_executions_agent_id"), "agent_executions", ["agent_id"], unique=False)
    op.create_index(op.f("ix_agent_executions_org_id"), "agent_executions", ["org_id"], unique=False)
    op.create_index(
        op.f("ix_agent_executions_workflow_id"), "agent_executions", ["workflow_id"], unique=False
    )
    op.create_table(
        "model_evaluations",
        sa.Column("model_id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("task_class", sa.String(length=100), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("evaluator_id", sa.String(length=36), nullable=False),
        sa.Column("org_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["evaluator_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["model_configs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["model_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id"),
    )
    op.create_index(op.f("ix_model_evaluations_model_id"), "model_evaluations", ["model_id"], unique=False)
    op.create_index(op.f("ix_model_evaluations_org_id"), "model_evaluations", ["org_id"], unique=False)
    op.create_table(
        "agent_state_events",
        sa.Column("execution_id", sa.String(length=36), nullable=False),
        sa.Column("previous_state", sa.String(length=40), nullable=False),
        sa.Column("state", sa.String(length=40), nullable=False),
        sa.Column("detail", sa.JSON(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("org_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["execution_id"],
            ["agent_executions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("execution_id", "sequence"),
    )
    op.create_index(
        op.f("ix_agent_state_events_execution_id"), "agent_state_events", ["execution_id"], unique=False
    )
    op.create_index(op.f("ix_agent_state_events_org_id"), "agent_state_events", ["org_id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_agent_state_events_org_id"), table_name="agent_state_events")
    op.drop_index(op.f("ix_agent_state_events_execution_id"), table_name="agent_state_events")
    op.drop_table("agent_state_events")
    op.drop_index(op.f("ix_model_evaluations_org_id"), table_name="model_evaluations")
    op.drop_index(op.f("ix_model_evaluations_model_id"), table_name="model_evaluations")
    op.drop_table("model_evaluations")
    op.drop_index(op.f("ix_agent_executions_workflow_id"), table_name="agent_executions")
    op.drop_index(op.f("ix_agent_executions_org_id"), table_name="agent_executions")
    op.drop_index(op.f("ix_agent_executions_agent_id"), table_name="agent_executions")
    op.drop_table("agent_executions")
    op.drop_index(op.f("ix_agent_work_org_id"), table_name="agent_work")
    op.drop_table("agent_work")
    op.drop_index(op.f("ix_provider_probes_org_id"), table_name="provider_probes")
    op.drop_table("provider_probes")
    op.drop_index(op.f("ix_model_policies_org_id"), table_name="model_policies")
    op.drop_table("model_policies")
    op.drop_index(op.f("ix_provider_credentials_org_id"), table_name="provider_credentials")
    op.drop_table("provider_credentials")
    # ### end Alembic commands ###
