"""Versioned semantic memory and pgvector index

Revision ID: dc1275532cfb
Revises: 4666ed0d2d17
"""

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op

revision = "dc1275532cfb"
down_revision = "4666ed0d2d17"
branch_labels = None
depends_on = None


def upgrade():
    if op.get_bind().dialect.name == "postgresql":
        op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "memory_cursors",
        sa.Column("source", sa.String(length=100), nullable=False),
        sa.Column("last_id", sa.String(), nullable=False),
        sa.Column("org_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id", "source"),
    )
    op.create_index(op.f("ix_memory_cursors_org_id"), "memory_cursors", ["org_id"], unique=False)
    op.create_table(
        "memory_entries",
        sa.Column("source_key", sa.String(length=120), nullable=False),
        sa.Column("kind", sa.String(length=60), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=True),
        sa.Column("agent_id", sa.String(length=36), nullable=True),
        sa.Column("conversation_id", sa.String(length=36), nullable=True),
        sa.Column("client_id", sa.String(length=36), nullable=True),
        sa.Column("visibility", sa.String(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("deleted", sa.Boolean(), nullable=False),
        sa.Column("index_status", sa.String(), nullable=False),
        sa.Column("embedding_fingerprint", sa.String(), nullable=False),
        sa.Column("index_error", sa.String(), nullable=False),
        sa.Column("updated_at", sa.Integer(), nullable=False),
        sa.Column("org_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id", "source_key"),
    )
    op.create_index(op.f("ix_memory_entries_index_status"), "memory_entries", ["index_status"], unique=False)
    op.create_index(op.f("ix_memory_entries_org_id"), "memory_entries", ["org_id"], unique=False)
    op.create_index(op.f("ix_memory_entries_project_id"), "memory_entries", ["project_id"], unique=False)
    op.create_table(
        "memory_grants",
        sa.Column("entry_id", sa.String(length=36), nullable=False),
        sa.Column("agent_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["entry_id"],
            ["memory_entries.id"],
        ),
        sa.PrimaryKeyConstraint("entry_id", "agent_id"),
    )
    op.create_table(
        "memory_versions",
        sa.Column("entry_id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("provenance", sa.JSON(), nullable=False),
        sa.Column("org_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["entry_id"],
            ["memory_entries.id"],
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("entry_id", "version"),
    )
    op.create_index(op.f("ix_memory_versions_entry_id"), "memory_versions", ["entry_id"], unique=False)
    op.create_index(op.f("ix_memory_versions_org_id"), "memory_versions", ["org_id"], unique=False)
    op.create_table(
        "memory_chunks",
        sa.Column("entry_id", sa.String(length=36), nullable=False),
        sa.Column("version_id", sa.String(length=36), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "embedding",
            pgvector.sqlalchemy.vector.VECTOR(dim=384).with_variant(sa.JSON(), "sqlite"),
            nullable=True,
        ),
        sa.Column("fingerprint", sa.String(), nullable=False),
        sa.Column("org_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["entry_id"],
            ["memory_entries.id"],
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["memory_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("version_id", "position"),
    )
    op.create_index(op.f("ix_memory_chunks_entry_id"), "memory_chunks", ["entry_id"], unique=False)
    op.create_index(op.f("ix_memory_chunks_org_id"), "memory_chunks", ["org_id"], unique=False)
    op.create_index(op.f("ix_memory_chunks_version_id"), "memory_chunks", ["version_id"], unique=False)
    op.create_index(
        "ix_memory_chunks_vector_hnsw",
        "memory_chunks",
        ["embedding"],
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    # ### end Alembic commands ###


def downgrade():
    op.drop_index("ix_memory_chunks_vector_hnsw", table_name="memory_chunks")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_memory_chunks_version_id"), table_name="memory_chunks")
    op.drop_index(op.f("ix_memory_chunks_org_id"), table_name="memory_chunks")
    op.drop_index(op.f("ix_memory_chunks_entry_id"), table_name="memory_chunks")
    op.drop_table("memory_chunks")
    op.drop_index(op.f("ix_memory_versions_org_id"), table_name="memory_versions")
    op.drop_index(op.f("ix_memory_versions_entry_id"), table_name="memory_versions")
    op.drop_table("memory_versions")
    op.drop_table("memory_grants")
    op.drop_index(op.f("ix_memory_entries_project_id"), table_name="memory_entries")
    op.drop_index(op.f("ix_memory_entries_org_id"), table_name="memory_entries")
    op.drop_index(op.f("ix_memory_entries_index_status"), table_name="memory_entries")
    op.drop_table("memory_entries")
    op.drop_index(op.f("ix_memory_cursors_org_id"), table_name="memory_cursors")
    op.drop_table("memory_cursors")
    # ### end Alembic commands ###
