"""persistent_auth_provider_wait_and_worker_health

Revision ID: e9c9f1ed55a6
Revises: b411d790aa01
"""
from alembic import op
import sqlalchemy as sa

revision = 'e9c9f1ed55a6'
down_revision = 'b411d790aa01'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_throttles',
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('resets_at', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('key_hash')
    )
    op.create_index(op.f('ix_login_throttles_resets_at'), 'login_throttles', ['resets_at'], unique=False)
    op.create_table('worker_heartbeats',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('started_at', sa.Integer(), nullable=False),
    sa.Column('last_seen', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_worker_heartbeats_last_seen'), 'worker_heartbeats', ['last_seen'], unique=False)
    op.create_table('auth_sessions',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('expires_at', sa.Integer(), nullable=False),
    sa.Column('revoked_at', sa.Integer(), nullable=True),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_sessions_expires_at'), 'auth_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_auth_sessions_org_id'), 'auth_sessions', ['org_id'], unique=False)
    op.create_index(op.f('ix_auth_sessions_user_id'), 'auth_sessions', ['user_id'], unique=False)
    op.add_column('workflows', sa.Column('wait_context', sa.JSON(), nullable=False, server_default=sa.text("'{}'")))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflows', 'wait_context')
    op.drop_index(op.f('ix_auth_sessions_user_id'), table_name='auth_sessions')
    op.drop_index(op.f('ix_auth_sessions_org_id'), table_name='auth_sessions')
    op.drop_index(op.f('ix_auth_sessions_expires_at'), table_name='auth_sessions')
    op.drop_table('auth_sessions')
    op.drop_index(op.f('ix_worker_heartbeats_last_seen'), table_name='worker_heartbeats')
    op.drop_table('worker_heartbeats')
    op.drop_index(op.f('ix_login_throttles_resets_at'), table_name='login_throttles')
    op.drop_table('login_throttles')
    # ### end Alembic commands ###
